// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetrofMusicStore.Data;

#nullable disable

namespace PetrofMusicStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230610185406_seeddatabase")]
    partial class seeddatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetrofMusicStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductBrand = "Yamaha",
                            ProductType = "Saxophone"
                        },
                        new
                        {
                            Id = 2,
                            ProductBrand = "Stradivarius",
                            ProductType = "Violin"
                        },
                        new
                        {
                            Id = 3,
                            ProductBrand = "Weltmeister",
                            ProductType = "Accordion"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
